name: intellix

services:
  avsi:
    image: docker.io/pellnetwork/intellix:v1.0.0
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL}
      - ETH_WS_URL=${ETH_WS_URL}
      - GATEWAY_ADDR=${GATEWAY_ADDR:-gateway:8949}
      - OPERATOR_KEY=${OPERATOR_KEY}
      - OPERATOR_BLS_KEY=${OPERATOR_BLS_KEY}
      - OPERATOR_KEY_MNEMONIC=${OPERATOR_KEY_MNEMONIC}
      - REGISTRY_ROUTER_ADDRESS=${REGISTRY_ROUTER_ADDRESS}
      - SERVICE_CHAIN_RPC_URL=${SERVICE_CHAIN_RPC_URL}
      - SERVICE_CHAIN_WS_URL=${SERVICE_CHAIN_WS_URL}
      - NETWORK=${NETWORK}
      - CHAIN_ID=${CHAIN_ID}
      - AGGREGATOR_RPC_URL=${AGGREGATOR_RPC_URL}
      - AGGREGATOR_INDEXER_START_HEIGHT=${AGGREGATOR_INDEXER_START_HEIGHT}
      - SERVICE_CHAIN_ID=${SERVICE_CHAIN_ID}
    ports:
      - "${HOST_DEBUG_PORT:-23346}:${DEBUG_PORT:-2345}"
      - "${HOST_SERVER_PORT:-36657}:26657"
    entrypoint: [ "bash", "/root/scripts/start_avsi.sh" ]
    volumes:
      - .intellix:/root/.intellix
      - ./scripts:/root/scripts
