name: intellix

services:
  avsi:
    image: docker.io/pellnetwork/intellix:v2.0.0
    environment:
      - ETH_RPC_URL=${ETH_RPC_URL}
      - ETH_WS_URL=${ETH_WS_URL}
      - GATEWAY_ADDR=${GATEWAY_ADDR:-gateway:8949}
      - OPERATOR_KEY=${OPERATOR_KEY}
      - OPERATOR_BLS_KEY=${OPERATOR_BLS_KEY}
      - OPERATOR_KEY_MNEMONIC=${OPERATOR_KEY_MNEMONIC}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - SEPOLIA_RPC_URL=${SEPOLIA_RPC_URL}
      - SEPOLIA_WS_URL=${SEPOLIA_WS_URL}
      - NETWORK=${NETWORK}
      - CHAIN_ID=${CHAIN_ID}
      - AGGREGATOR_RPC_URL=${AGGREGATOR_RPC_URL}
      - AGGREGATOR_INDEXER_START_HEIGHT=${AGGREGATOR_INDEXER_START_HEIGHT}
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
      - ECC_PUBLIC_KEY=${ECC_PUBLIC_KEY}
    ports:
      - "${HOST_DEBUG_PORT:-23346}:${DEBUG_PORT:-2345}"
      - "${HOST_SERVER_PORT:-36657}:26657"
    entrypoint: [ "bash", "/root/scripts/start_avsi.sh" ]
    volumes:
      - "${HOST_PELLDVS_HOME:-./.avsi}:/root/.pelldvs"
      - ./scripts:/root/scripts
