name: intellix

services:

  abci:
    image: docker.io/pellnetwork/intellix:v1.0.0
    entrypoint: [ "bash", "/root/scripts/entrypoint.sh" ]
    environment:
      - FAST_SYNC=${FAST_SYNC:-true}
      - MONIKER=${MONIKER:-local-test}
      - SEEDS=${SEEDS:-""}
      - RPC_SERVERS=${RPC_SERVERS:-""}
      - IS_ARCHIVE=${IS_ARCHIVE:-false}
    volumes:
      - .intellix:/root/.intellix
      - ./scripts:/root/scripts
    ports:
      - 1317:1317
      - 9090:9090
      - 26656:26656
      - 26657:26657

